# .streamlit/secrets.toml
AMADEUS_API_KEY = "X0GWDRRoNmn6ORcSkfhOBGjiR75s0PIo"
AMADEUS_API_SECRET = "2sdyh8nvAi89w0iL"

RAPIDAPI_KEY = "5a26e14d6amsheeb99b61b3ff65ep17583cjsn4eb17402fec4"

AIRLABS_KEY = "15151c68-6858-4cc2-a819-33b87bfc7651"
